### ISSUE TITLE
jvm_classpath with wildcards attempts to read all files not just those ending with *.jar

### ISSUE THREAD

**Issue by kjniemi** [nginx-clojure/nginx-clojure#102]
When jvm_classpath, which was added in #95, is used with wildcards it attempts to read all files in a library and not just the ones ending with *.jar like the Oracle JVM does.

**Comment by xfeep** [comment]
@kjniemi Thank you for reporting this issue.
It 's true that `jvm_classpath` with character (*) has the different behavior from  Oracle JVM. The doc from Oralce says 
>Class path entries can contain the base name wildcard character (*), which is considered equivalent to specifying a list of all of the files in the directory with the extension .jar or .JAR. 

With `jvm_classpath` if a class path entry name ends with wildcard character, all direct sub files, including jar, zip, direct sub directories, and so on will be in the list of the actual class path entries and sub directories are not searched recursively. Although it's my mistake that I was not read the doc carefully but I do prefer the current behavior from `jvm_classpath` :-) . Because it is very common that some folders contains classes/resource files in the lib directory. e.g.

```nginx
jvm_classpath libs/*;
```

and the structure of libs is 

```
libs/
    /a.jar
    /classes -------- a directory contains java class files
    /resources -------a directory contains some resource files

```

**Comment by kjniemi** [comment]
@xfeep Understood and I do respect your choice - the way you intended it does make sense in some situations. Could you please document it a bit more verbosely ;-)

**Comment by xfeep** [comment]
@kjniemi 
> Understood and I do respect your choice - the way you intended it does make sense in some situations. 

Thanks for your understanding :-)
>Could you please document it a bit more verbosely ;-)

Sure, my pleasure. I have updated [the doc](https://github.com/nginx-clojure/nginx-clojure.github.io/blob/master/Directives.md#jvm_classpath) which is published as https://nginx-clojure.github.io/directives.html#jvm_classpath.

**Comment by kjniemi** [comment]
@xfeep works for me :-)
