### ISSUE TITLE
nginx reload will cause connection reset without response

### ISSUE THREAD

**Issue by sunjunzero** [nginx-clojure/nginx-clojure#118]
1. Write a handler to return the response in a certain time (60s).
2. start nginx-clojure server with correct configurations
3. curl the url
4. do nginx-clojure reload to refresh configurations

Except:
The curl should get the correct response.

Actual:
The curl failed with empty response
with tcpdump, nginx-clojure reset the connection after the handler return.

**Comment by xfeep** [comment]
@sunjunzero 
Hi, I can not reproduce it.
Could you please show us your nginx.conf?  Which type of OS do you use?

**Comment by sunjunzero** [comment]
@xfeep 
Sorry that I have not tried all the cases.
I have download the 0.4.4 version and try to reproduce it.

With "jvm_workers 0;", the return is correctly.
With "jvm_workers 8;" (any numbers), this issue will happen.
I guess the main thread is interrupted while the work threads is still working, and this cause the issue.


Here's the conf:

[nginx.conf.txt](https://github.com/nginx-clojure/nginx-clojure/files/251490/nginx.conf.txt)

**Comment by xfeep** [comment]
@sunjunzero 
Thank you very much!
It's a bug about thread pool mode / hijacked request.
I'll try to fix it over the next few days.

**Comment by xfeep** [comment]
@sunjunzero 
Hi, commit 7a31310 should fix it. Please try again. Thanks!

**Comment by sunjunzero** [comment]
@xfeep 
I have verified that response could be returned correctly for thread pool mode / hijacked request after reload. 

But found a new issue:
If a hijacked request have no response, the work process could not be stopped after the client has disconnected.
Well written applications should not enter this case.
Do you think this should be fixed in nginx-clojure?

I have checked ws connections works as expected.

Here's sample conf:
[nginx.conf.txt](https://github.com/nginx-clojure/nginx-clojure/files/254327/nginx.conf.txt)

**Comment by xfeep** [comment]
@sunjunzero 
Thanks for your verification.
By default nginx-clojure won't check a broken client unless sending happens. 
Because a hijacked request without response is not a normal case so we don't think it is an issue from nginx-clojure.
BTW, we can still send a null message to force nginx-clojure to check a broken client. e.g. In your sample  
```nginx
location /groovy {
          handler_type 'groovy';
          handler_code '
               import nginx.clojure.java.NginxJavaRequest;
               import nginx.clojure.java.NginxJavaRingHandler;
               import java.util.Map;
               public class HelloGroovy implements NginxJavaRingHandler {
                  public Object[] invoke(Map<String, Object> request){
                     NginxJavaRequest r = (NginxJavaRequest)request;
                     //send a null message to force nginx-clojure to check a broken client.
                     r.hijack(false).send(null, true, false); 
                     return null
                  }
               }
          ';
       }
```
In the future we maybe can introduce a new directive which is similar to [lua_check_client_abort](https://github.com/openresty/lua-nginx-module#lua_check_client_abort).

**Comment by sunjunzero** [comment]
It's ok for me. Thanks for your fix 👍 .

**Comment by xfeep** [comment]
@sunjunzero 
My pleasure! I would not have fixed it so quickly without your so detail sample.
It's great that your verification covers most cases and is very helpful to us.

**Comment by alex-sherwin** [comment]
@xfeep 

I'm having a tough time with getting nginx-clojure to not drop an in-flight request inside a rewrite handler.

When I have an in-flight request running in Java code that starts just before a `reload` signal is sent to the nginx process, which calls `NginxJavaRequest.setVariable(...)` the invocation hangs indefinitely (forever)

I've tried using a JVM exit handler and a `ReadWriteLock` pattern which ensures that the JVM exit handler cannot complete until after all in-flight requests are finished (confirmed with logging), yet the problem still persists.

I've tried a hack which times out on the `NginxJavaRequest.setVariable(...)` invocation after 100ms, assumes the client connection is bad at this point (due to `reload` signal) and then returns a response from the `NginxJavaRingHandler.invoke(..)` anyways.  I tried having it return `null` and `PHASE_DONE` and in both cases the HTTP client still receives an invalid/broken response

When this scenario occurs I've also tried what was recommended in this issue with `                 r.hijack(false).send(null, true, false);` and then returning `null` or `PHASE_DONE` and get the same result (invalid/broken response down to HTTP client) and this exception is thrown:

```
2017/10/13 16:46:29.521 [nginx-clojure-worker-2] ERROR [com.acadiasoft.apigw.ApiGateway] [pno:3] - Task java.util.concurrent.FutureTask@7128fc8d rejected from java.util.concurrent.ThreadPoolExecutor@1079202f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7128fc8d rejected from java.util.concurrent.ThreadPoolExecutor@1079202f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at nginx.clojure.java.NginxJavaRequest.addListener(NginxJavaRequest.java:442)
        at nginx.clojure.NginxHttpServerChannel.<init>(NginxHttpServerChannel.java:51)
        at nginx.clojure.java.NginxJavaHandler.hijack(NginxJavaHandler.java:181)
        at nginx.clojure.java.NginxJavaRequest.hijack(NginxJavaRequest.java:470)
        at com.[MYCOMPANY].[MYHANDLER].doInvoke([MYHANDLER].java:[REDACTED])
```

What is the correct pattern to gracefully handle an in-flight request during an nginx `reload`?  I can't find anything described in the documentation

Thank you very much

**Comment by xfeep** [comment]
@alex-sherwin Please try to increase the value of  NGX_HTTP_CLOJURE_RELOAD_DELAY_MAX_TIME which is 30s by default. It is declared at ngx_http_clojure_mem.h.

**Comment by alex-sherwin** [comment]
@xfeep 
In my scenario this is all happening on any in-flight request, not just long running ones.  I've got requests which process in < 10ms and they have this issue.  Anytime the `NginxJavaRingHandler.invoke` is in-flight while a nginx `reload` signal is triggered, those requests always fail

Is there a basic pattern that's supposed to be followed to prevent this?

I did try increasing `NGX_HTTP_CLOJURE_RELOAD_DELAY_MAX_TIME` anyways, but it had no affect

**Comment by xfeep** [comment]
Could you please give us a minimal example to produce this issue?

**Comment by alex-sherwin** [comment]
Hi @xfeep 

I put together this repo this morning, it's the smallest example I could put together.  It uses docker to build a custom nginx image, then another image based on that with a maven based java app

It has a bunch of shell scripts to build, run, curl, reload signals and cleanup and the readme describes how to use it

Please see https://github.com/alex-sherwin/nginx-clojure-reload

Thanks

**Comment by xfeep** [comment]
@alex-sherwin we created a new issue #193 and  fixed it. Please try the master branch
