### ISSUE TITLE
Using the asynchronous socket mode

### ISSUE THREAD

**Issue by dgrnbrg** [nginx-clojure/nginx-clojure#12]
Hi, I am very interested in using the async sockets you provide to the client libs. If I use them with core.async, will core.async still initialize its own thread pool and run its go blocks there? If not, could you make an example of the async sockets used in Clojure?

**Comment by xfeep** [comment]
In v0.4.0 we can use HttpServerChannel to send response asynchronously  easily, e.g. use it for 
1. [Server Sent Event (SSE) (since 0.2.5)](http://nginx-clojure.github.io/more.html#34-server-channel-for-long-polling--server-sent-events-sse)
2. [Http Long Polling (since 0.2.5)](http://nginx-clojure.github.io/more.html#34-server-channel-for-long-polling--server-sent-events-sse)
3. [WebSocket (since 0.4.0).](http://nginx-clojure.github.io/more.html#38--sever-side-websocket)
