### ISSUE TITLE
Pub/Sub Among Nginx Worker Processes

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#165]
@xfeep can you please explain this and provide a real example of how this works.   

thanks.

**Comment by xfeep** [comment]
Please read the explanation from http://nginx-clojure.github.io/subpub.html .

There're two java examples and three clojure examples.

1. java examples

* long poll example
 https://github.com/nginx-clojure/nginx-clojure/blob/v0.4.4/test/java/nginx/clojure/java/GeneralSet4TestNginxJavaRingHandler.java#L176

* sse example
 https://github.com/nginx-clojure/nginx-clojure/blob/v0.4.4/test/java/nginx/clojure/java/GeneralSet4TestNginxJavaRingHandler.java#L211


2. clojure examples

* long poll example
  https://github.com/nginx-clojure/nginx-clojure/blob/v0.4.4/test/clojure/nginx/clojure/ring_handlers_for_test.clj#L131

* sse example
  https://github.com/nginx-clojure/nginx-clojure/blob/v0.4.4/test/clojure/nginx/clojure/ring_handlers_for_test.clj#L120

* websocket example
  https://github.com/nginx-clojure/nginx-clojure/tree/v0.4.4/example-projects/clojure-web-example

**Comment by knasim** [comment]
@xfeep  - thank you  for sending.  

one more thing - i need to get a good picture about performance impact on nginx when using you're code.  

1.  Nginx-clojure attaches a JVM to each nginx worker.  What are the effects of this in your opinion ?

2. If the JVM dies does that affect the worker thread?    

3. When nginx recycles the worker threads what happens to the JVM that is attached to each worker?

**Comment by xfeep** [comment]
>Nginx-clojure attaches a JVM to each nginx worker. What are the effects of this in your opinion ?

Typically a nginx worker is an event driven process which is created by nginx master process.In most cases the number of nginx worker processes won't be greater than the number of hard cpu thread.

>If the JVM dies does that affect the worker thread?

Because nginx worker process and JVM process is the exact same process so JVM dies means the same worker process dies. But nginx master process will recreate another worker process after one died so we need not be too worried.

>When nginx recycles the worker threads what happens to the JVM that is attached to each worker?

I can not catch the meaning about `nginx recycles the worker threads` . Typically nginx is not thread-pool based but event driven so it won't recycle the worker threads.

**Comment by knasim** [comment]
Good point - "typically nginx is not thread-pool based but event driven so it won't recycle the worker threads"

What i mean by recycle the workers is if you do nginx reload because you changed something in nginx configuration file - then what happens to the attached JVM on reload ?

**Comment by xfeep** [comment]
The new ones will be created and use new configurations and the old JVMs, viz. old nginx worker processes,  will quit eventually.
