### ISSUE TITLE
good effort

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#201]
@xfeep  - This indeed is a good effort that alludes to the creativity that one can do with NGINX.
However it does not have practical value because you are adding business logic to NGINX and that may not sit in well with the SDLC models of different teams.  NGINX really just needs to do what it is designed to do with limited externally managed capabilities.

**Comment by xfeep** [comment]
@kanwei Thank you!

We never think it can sit with every team but if there's any team need it it's enough.

Many nginx modules were created beyond the original design because the original design did not sit well with their practical requirements.

Therefore, the decisive thing is the real world requirement rather than the original design.

BTW weself are also the user of this project.
