### ISSUE TITLE
Small example project?

### ISSUE THREAD

**Issue by ptaoussanis** [nginx-clojure/nginx-clojure#91]
Hi Zhang,

Have you thought to maybe include some kind of simple example project for users to download + run to experiment with (learn) nginx-clojure?

The [quick start guide](http://nginx-clojure.github.io/quickstart.html) looks good, but maybe still a bit intimidating (scary) for people who are not familiar with configuring nginx modules, etc.?

For example, in the quick start guide, you have an inline handler like:
```clojure
(fn[req]
  {:status 200,
   :headers {"content-type" "text/plain"},
   :body  "Hello Clojure & Nginx!"})
```

But as a Clojure developer - I think: how can I connect nginx-clojure to my Clojure application if I am using a Compojure router, etc. The documents say this is possible, but I could not find somewhere to say exactly how?

So maybe a useful example project could include:
1. A small Clojure application using Compojure and a few routes with simple text responses: "route 1 response", "route 2 response", etc.
2. The right `nginx.conf` for this small Clojure application.
3. Any special startup scripts that may be needed.
4. Maybe some comments about: is there anything special we need to do for sessions, etc.

Some questions that I still have after looking at the documents:
1. Is it possible to convert _any_ standard Jetty Clojure application to use `nginx-clojure`?
2. Is this usually difficult (it needs a lot of work), or is it usually quite easy?
3. Are there any limitations (problems/disadvantages) with using `nginx-clojure` instead of something like Jetty or http-kit?
4. Is better performance the main advantage to using `nginx-clojure` instead of something like Jetty or http-kit?

The [nginx-clojure performance](https://github.com/ptaoussanis/clojure-web-server-benchmarks) looks very good. I think probably some Clojure developers would look more closely at `nginx-clojure` if these few things could be a bit more clear.

Does that make sense?

I hope these comments are useful, good luck with the project!

(Also, I will try release the new Sente version later today).

**Comment by xfeep** [comment]
Hi Taoussanis,
Thank you very much!  :+1:  I think your suggestions are really helpful especially to those who know little about Nginx.

> Have you thought to maybe include some kind of simple example project for users to download + run to experiment with (learn) nginx-clojure?

I had not thought to do such thing but I will do it later :-) .

>The [quick start guide](http://nginx-clojure.github.io/quickstart.html) looks good, but maybe still a bit intimidating (scary) for people who are not familiar with configuring nginx modules, etc.?
>But as a Clojure developer - I think: how can I connect nginx-clojure to my Clojure application if I am using a Compojure router, etc. The documents say this is possible, but I could not find somewhere to say exactly how?

Because Compojure routers are really ring handlers so I had thought the document about [how to use external ring handlers](http://nginx-clojure.github.io/configuration.html#232-reference-of-external-ring-handlers) (viz. not inline ring handlers) is enough, e.g. 
In nginx.conf
```nginx
location /myapp {
          content_handler_type 'clojure';
          content_handler_name 'example/my-app';
}
```
```clojure
(ns example
  (:require [compojure.core :refer :all]
            [compojure.route :as route]))

(defroutes my-app
  (GET "/" [] "<h1>Hello World</h1>")
  (route/not-found "<h1>Page not found</h1>"))
```

>So maybe a useful example project could include:
1. A small Clojure application using Compojure and a few routes with simple text responses: "route 1 response", "route 2 response", etc.
2. The right `nginx.conf` for this small Clojure application.
3. Any special startup scripts that may be needed.
4. Maybe some comments about: is there anything special we need to do for sessions, etc.

Thanks for your so detail suggestions! In the coming example project for clojure devs I will includes all your mentioned here.

>Some questions that I still have after looking at the documents:
1. Is it possible to convert _any_ standard Jetty Clojure application to use `nginx-clojure`?

Yes.

>`2.`  Is this usually difficult (it needs a lot of work), or is it usually quite easy?

It depends which I/O mode we choose. Generally use 1 nginx worker + thread pool mode is the simplest choice if one CPU is enough to handle HTTP server I/O. If We don't need the feature about that  the nginx master process will auto-restart our JVM process (viz. nginx worker process) when the JVM is crashed, we can even can try to use an [embed nginx-clojure](http://nginx-clojure.github.io/embed.html) which have no specially differences with other ring-compatible servers.
If we try to use more than one nginx worker processes there will be more than one jvm instances so to get synchronized session information we can not use the default memory based session manger.
Instead we may consider to use either of 

1. Cookie based Session Store  viz. storing all session attribute information into cookies.
1. Shared HashMap among processes in the same machine ,e.g. [Chronicle Map](https://github.com/OpenHFT/Chronicle-Map)
1. External Session Store,  e.g.  Redis / MySQL / Memcached Session Store

Once our app can work with more than one nginx worker processes in one computer it means our app can also be horizontally scaled to a cluster which has many nginx instances on many different computers, typically we also use a router/balancer (e.g. [HAProxy](http://www.haproxy.org/), Nginx, LVS, F5 etc.) in the front of this app cluster. Sometime we even use a  router/balancer cluster  such as [Keepalived](http://www.keepalived.org/) + [HAProxy](http://www.haproxy.org/), Keepalived + nginx, or Keepalived + [LVS](http://www.linuxvirtualserver.org/)  in the front of this app cluster.

> `3`. Are there any limitations (problems/disadvantages) with using `nginx-clojure` instead of something like Jetty or http-kit?

Compared with Jetty or http-kit, nginx-clojure really has some disadvantages :

1. It is more complex if we want to use all full features from it. It has too many choices and some choices maybe will affect our app coding. e.g. use only one nginx worker process or more than one, use thread pool or coroutine based socket or asynchronous socket to handle external I/O (e.g. access remote http service/MySQL).
2. Debug is more difficult before v0.4.1. Before v0.4.1 we need to use JVM remote debug function to debug our java/clojure ring handlers. Since v0.4.1 which has APIs for embedding nginx-clojure so we can debug our java/clojure ring handlers by starting an embed nginx-clojure.
3. Nginx.conf seems strange to most clojure devs.
and so on.

> `4`. Is better performance the main advantage to using `nginx-clojure` instead of something like Jetty or http-kit?

No. I don't think so although under large amount of connections nginx-clojure will get better performance. I think we use nginx-clojure when we meet either or some of cases :

1.  We need the auto-restart feature to auto-restart our JVM when it is crashed.
2.  We want to use nignx to do somethings which general Java servers can not do easily or efficiently, e.g. limiting connections/request rate, better static files service, http proxy cache for inner requests, image filter and etc, although we can use nginx+java server but use nginx-clojure will be more easily for deployment and cost less memory and cpu.
3.  We want to implement a dynamic router/balancer with nginx + clojure/java. Here is  [a simple example](https://dzone.com/articles/10-lines-clojure-code-build-0) and there also has  [another example](http://stackoverflow.com/questions/31951813/http-request-response-with-response-from-a-different-server/32016344#32016344) on StackOverflow.
4.  Secure existing service by nginx + clojure/java, e.g. writing one nginx access handler by clojure/java
5.  We can not bear the burden of thread pool and we want to try coroutine based socket from nginx-clojure.
6.  We hit the issue that JVM can not efficiently handle more than 32G RAM and we try to use more than one nginx worker processes (viz. JVM instances on nginx-clojure)  , e.g. we have 128G RAM and use 5 nginx worker processes every of which uses 24G RAM and left 8G to OS and other processes.

So in some cases nginx-clojure even can work together with Jetty or http-kit  and not just works as a replacement to them.  e.g. We even can start a jetty/http-kit instance within nginx-clojure jvm-init handler so that nginx will restart out http-kit instance if jvm is crashed or we detect some unrecoverable error and do `System.exit` in our  detector thread to let nginx auto-restart out jetty/http-kit instance.

> The [nginx-clojure performance](https://github.com/ptaoussanis/clojure-web-server-benchmarks) looks very good. I think probably some Clojure developers would look more closely at `nginx-clojure` if these few things could be a bit more clear.
> Does that make sense?
> I hope these comments are useful, good luck with the project!

I think you're right and your comments are very very useful. Thank you again.  Please feel free to give any suggestion!

BTW I think this reply is a little too long so I will re-manage them into a FAQ later.

**Comment by xfeep** [comment]
BTW more examples about compojure and ring can be found from [nginx-clojure testing codes about ring and compojure](https://github.com/nginx-clojure/nginx-clojure/blob/master/test/clojure/nginx/clojure/ring_handlers_for_test.clj#L89). And we can use below configurations in nginx.conf

```nginx
       location /ringCompojure {
         content_handler_type 'clojure';
         content_handler_code '
           (do
             (use \'[compojure.core])
             (use \'[nginx.clojure.ring-handlers-for-test])
             (context "/ringCompojure" [] ring-compojure-test-handler)
           )
         ';
         location /ringCompojure/ws- {
           auto_upgrade_ws on;
         }
       }
```

**Comment by xfeep** [comment]
I think [the testing client code](https://github.com/nginx-clojure/nginx-clojure/blob/master/test/clojure/nginx/clojure/test_all.clj#L271)  is also helpful to us to understand the server side  [nginx-clojure testing code about ring and compojure](https://github.com/nginx-clojure/nginx-clojure/blob/master/test/clojure/nginx/clojure/ring_handlers_for_test.clj#L89).

**Comment by xfeep** [comment]
@ptaoussanis Hi Taoussanis, I have finished  [a simple clojure web example project](https://github.com/nginx-clojure/nginx-clojure/tree/master/example-projects/clojure-web-example). Thanks again!

**Comment by ptaoussanis** [comment]
Awesome! Sorry for not replying properly- I have been _very_ busy with work lately.

This looks great though, I will try look through everything properly when I have some free time again. Congratulations on the new release!

Keep up the great work :-) :+1:

**Comment by xfeep** [comment]
Thanks! No rush. Welcome your suggestions anytime :-)
