### ISSUE TITLE
add directive `jvm_classpath`  which supports wildcard character *

### ISSUE THREAD

**Issue by xfeep** [nginx-clojure/nginx-clojure#95]
e.g.

```nginx
jvm_classpath '/opt/mylib/*:/opt/myclasses';
```

If  if the directory `/opt/mylib` contains a.jar, b.jar, and c.jar, then the class path `/opt/mylib/*` will be expanded into `/opt/mylib/a.jar:/opt/mylib/b.jar:/opt/mylib/c.jar`). So as the above example the result  is `/opt/mylib/a.jar:/opt/mylib/b.jar:/opt/mylib/c.jar:/opt/myclasses` which will be the value of the system property java.class.path, viz. it is equivalent to 

```nginx
jvm_options '-Djava.class.path=/opt/mylib/a.jar:/opt/mylib/b.jar:/opt/mylib/c.jar:/opt/myclasses';
```

This feature will make #94 be fixed mostly.

**Comment by soufrk** [comment]
Results in,
`Error: Could not find or load main class nginx.clojure.DiscoverJvm
nginx: [error] detect jvm error, cmd : java -Djava.class.path=/home/soufrk/jee-workspace/nginx-clojure-demo/target/: nginx.clojure.DiscoverJvm 
, result : 
nginx: [error] can not find installed JRE/JDK
`

Here's the **configuration**,
`jvm_path auto;
jvm_classpath '/home/pftblr-dev-ubuntu/jee-workspace/nginx-clojure-demo/target/'; #windows user should use ';' as the separator
`

I think that's because the classpath value gets overridden, with the location where I intend to provide only compiled JAR to be loaded.

Did I make the problem clear ?
