### ISSUE TITLE
Error compiling nginx-clojure module with nginx

### ISSUE THREAD

**Issue by chenfisher** [nginx-clojure/nginx-clojure#99]
Hi,

I get the following error when compiling nginx-clojure module with nginx:

```
nginx-clojure/src/c/ngx_http_clojure_mem.c:2250:14: error: 'ngx_http_clojure_websocket_alloc' defined but not used [-Werror=unused-function]
 static void *ngx_http_clojure_websocket_alloc(void *opaque, u_int items, u_int size) {
              ^
nginx-clojure/src/c/ngx_http_clojure_mem.c:2256:13: error: 'ngx_http_clojure_websocket_free' defined but not used [-Werror=unused-function]
 static void ngx_http_clojure_websocket_free(void *opaque, void *address) {
             ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/c/ngx_http_clojure_mem.o] Error 1
```

I can work around this error by specifying ```--with-cc-opt=-Wno-error``` to ```./configure```, but I think it's better to fix this on your end

Thanks

**Comment by xfeep** [comment]
@chenfisher Thanks for your report!
It seems there's none of SHA1 implementation which is needed by nginx-clojure websocket feature.
If you don't need websocket feature it is OK, otherwise please install libssl-dev/openssl-devel first them rebuild nginx-clojure.
I will fix these compile errors soon by putting `#if (NGX_HAVE_SHA1)` around these two functions (`ngx_http_clojure_websocket_alloc`, `ngx_http_clojure_websocket_free`) .

**Comment by xfeep** [comment]
@chenfisher Sorry for last incomplete reply. I correct it here:
These two functions (`ngx_http_clojure_websocket_alloc`, `ngx_http_clojure_websocket_free`) will be used when both SHA1 and zlib  are found. SHA1 implementation  is needed by nginx-clojure websocket feature and zlib  is needed by Per-message Compression Extensions (PMCEs) for WebSocket. I think generally on most of linux distrubutions zlib is included by default. If zlib implementation can not be found gzip feature of nginx won't work too.

**Comment by xfeep** [comment]
@chenfisher  commit 732ab4d  fixs these compile error now. Please try it. Thanks!

**Comment by chenfisher** [comment]
Thanks @xfeep !
